# .streamlit/secrets.toml

CONN_STR = "Driver={ODBC Driver 17 for SQL Server};Server=alternamax.database.windows.net;Database=free-sql-db-6559757;Uid=alternamax;Pwd=Tuerquita123?;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
